version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  postgres_test:
    image: postgres
    ports:
      - '5434:5432'
    env_file:
      - .env.test

volumes:
  postgres:
